name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/Validatum/test/Validatum.Tests.csproj
    - name: Build Pipelines
      run: dotnet build src/Validatum/test/Validatum.Tests.csproj --configuration Release --no-restore
    - name: Test Pipelines
      run: dotnet test src/Validatum/test/Validatum.Tests.csproj --no-restore --verbosity quiet
